("undefined"==typeof Crypto||!Crypto.util)&&function(){var a=window.Crypto={},b=a.util={rotl:function(a,b){return a<<b|a>>>32-b},rotr:function(a,b){return a<<32-b|a>>>b},endian:function(a){if(a.constructor==Number)return b.rotl(a,8)&16711935|b.rotl(a,24)&4278255360;for(var c=0;c<a.length;c++)a[c]=b.endian(a[c]);return a},randomBytes:function(a){for(var b=[];0<a;a--)b.push(Math.floor(256*Math.random()));return b},bytesToWords:function(a){for(var b=[],c=0,f=0;c<a.length;c++,f+=8)b[f>>>5]|=a[c]<<24-
f%32;return b},wordsToBytes:function(a){for(var b=[],c=0;c<32*a.length;c+=8)b.push(a[c>>>5]>>>24-c%32&255);return b},bytesToHex:function(a){for(var b=[],c=0;c<a.length;c++)b.push((a[c]>>>4).toString(16)),b.push((a[c]&15).toString(16));return b.join("")},hexToBytes:function(a){for(var b=[],c=0;c<a.length;c+=2)b.push(parseInt(a.substr(c,2),16));return b},bytesToBase64:function(a){if("function"==typeof btoa)return btoa(c.bytesToString(a));for(var b=[],g=0;g<a.length;g+=3)for(var f=a[g]<<16|a[g+1]<<8|
a[g+2],h=0;4>h;h++)8*g+6*h<=8*a.length?b.push("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(f>>>6*(3-h)&63)):b.push("=");return b.join("")},base64ToBytes:function(a){if("function"==typeof atob)return c.stringToBytes(atob(a));for(var a=a.replace(/[^A-Z0-9+\/]/ig,""),b=[],g=0,f=0;g<a.length;f=++g%4)0!=f&&b.push(("ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a.charAt(g-1))&Math.pow(2,-2*f+8)-1)<<2*f|"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".indexOf(a.charAt(g))>>>
6-2*f);return b}};a.mode={};a=a.charenc={};a.UTF8={stringToBytes:function(a){return c.stringToBytes(unescape(encodeURIComponent(a)))},bytesToString:function(a){return decodeURIComponent(escape(c.bytesToString(a)))}};var c=a.Binary={stringToBytes:function(a){for(var b=[],c=0;c<a.length;c++)b.push(a.charCodeAt(c)&255);return b},bytesToString:function(a){for(var b=[],c=0;c<a.length;c++)b.push(String.fromCharCode(a[c]));return b.join("")}}}();
(function(){var a=Crypto,b=a.util,c=a.charenc,d=c.UTF8,e=c.Binary,g=a.SHA1=function(a,c){var d=b.wordsToBytes(g._sha1(a));return c&&c.asBytes?d:c&&c.asString?e.bytesToString(d):b.bytesToHex(d)};g._sha1=function(a){a.constructor==String&&(a=d.stringToBytes(a));var c=b.bytesToWords(a),e=8*a.length,a=[],g=1732584193,k=-271733879,n=-1732584194,l=271733878,q=-1009589776;c[e>>5]|=128<<24-e%32;c[(e+64>>>9<<4)+15]=e;for(e=0;e<c.length;e+=16){for(var i=g,o=k,r=n,p=l,s=q,t=0;80>t;t++){if(16>t)a[t]=c[e+t];else{var u=
a[t-3]^a[t-8]^a[t-14]^a[t-16];a[t]=u<<1|u>>>31}u=(g<<5|g>>>27)+q+(a[t]>>>0)+(20>t?(k&n|~k&l)+1518500249:40>t?(k^n^l)+1859775393:60>t?(k&n|k&l|n&l)-1894007588:(k^n^l)-899497514);q=l;l=n;n=k<<30|k>>>2;k=g;g=u}g+=i;k+=o;n+=r;l+=p;q+=s}return[g,k,n,l,q]};g._blocksize=16;g._digestsize=20})();
(function(){var a=Crypto,b=a.util,c=a.charenc,d=c.UTF8,e=c.Binary;a.HMAC=function(a,c,h,j){c.constructor==String&&(c=d.stringToBytes(c));h.constructor==String&&(h=d.stringToBytes(h));h.length>4*a._blocksize&&(h=a(h,{asBytes:!0}));for(var m=h.slice(0),h=h.slice(0),k=0;k<4*a._blocksize;k++)m[k]^=92,h[k]^=54;a=a(m.concat(a(h.concat(c),{asBytes:!0})),{asBytes:!0});return j&&j.asBytes?a:j&&j.asString?e.bytesToString(a):b.bytesToHex(a)}})();
(function(){var a=Crypto,b=a.util,c=a.charenc,d=c.UTF8,e=c.Binary;a.PBKDF2=function(c,f,h,j){c.constructor==String&&(c=d.stringToBytes(c));f.constructor==String&&(f=d.stringToBytes(f));for(var m=j&&j.hasher||a.SHA1,k=j&&j.iterations||1,n=[],l=1;n.length<h;){var q;q=f.concat(b.wordsToBytes([l]));for(var i=q=a.HMAC(m,q,c,{asBytes:!0}),o=1;o<k;o++)for(var i=a.HMAC(m,i,c,{asBytes:!0}),r=0;r<q.length;r++)q[r]^=i[r];n=n.concat(q);l++}n.length=h;return j&&j.asBytes?n:j&&j.asString?e.bytesToString(n):b.bytesToHex(n)}})();
(function(){function a(a,c,d){for(var e=4*a._blocksize,d=d.slice(0),g=0;g<c.length;g++)0==g%e&&a._encryptblock(d,0),c[g]^=d[g%e]}Crypto.mode.OFB={encrypt:a,decrypt:a}})();
(function(){function a(a,b){for(var c=0,d=0;8>d;d++){b&1&&(c^=a);var e=a&128,a=a<<1&255;e&&(a^=27);b>>>=1}return c}for(var b=Crypto,c=b.util,d=b.charenc.UTF8,e=[99,124,119,123,242,107,111,197,48,1,103,43,254,215,171,118,202,130,201,125,250,89,71,240,173,212,162,175,156,164,114,192,183,253,147,38,54,63,247,204,52,165,229,241,113,216,49,21,4,199,35,195,24,150,5,154,7,18,128,226,235,39,178,117,9,131,44,26,27,110,90,160,82,59,214,179,41,227,47,132,83,209,0,237,32,252,177,91,106,203,190,57,74,76,88,207,
208,239,170,251,67,77,51,133,69,249,2,127,80,60,159,168,81,163,64,143,146,157,56,245,188,182,218,33,16,255,243,210,205,12,19,236,95,151,68,23,196,167,126,61,100,93,25,115,96,129,79,220,34,42,144,136,70,238,184,20,222,94,11,219,224,50,58,10,73,6,36,92,194,211,172,98,145,149,228,121,231,200,55,109,141,213,78,169,108,86,244,234,101,122,174,8,186,120,37,46,28,166,180,198,232,221,116,31,75,189,139,138,112,62,181,102,72,3,246,14,97,53,87,185,134,193,29,158,225,248,152,17,105,217,142,148,155,30,135,233,
206,85,40,223,140,161,137,13,191,230,66,104,65,153,45,15,176,84,187,22],g=[],f=0;256>f;f++)g[e[f]]=f;for(var h=[],j=[],m=[],k=[],n=[],l=[],f=0;256>f;f++)h[f]=a(f,2),j[f]=a(f,3),m[f]=a(f,9),k[f]=a(f,11),n[f]=a(f,13),l[f]=a(f,14);var q=[0,1,2,4,8,16,32,64,128,27,54],i=[[],[],[],[]],o,r,p,s=b.AES={encrypt:function(a,e,f){var f=f||{},a=d.stringToBytes(a),g=f.iv||c.randomBytes(4*s._blocksize),e=e.constructor==String?b.PBKDF2(e,g,32,{asBytes:!0}):e,h=f.mode||b.mode.OFB;s._init(e);h.encrypt(s,a,g);return c.bytesToBase64(f.iv?
a:g.concat(a))},decrypt:function(a,e,f){var f=f||{},a=c.base64ToBytes(a),g=f.iv||a.splice(0,4*s._blocksize),e=e.constructor==String?b.PBKDF2(e,g,32,{asBytes:!0}):e,f=f.mode||b.mode.OFB;s._init(e);f.decrypt(s,a,g);return d.bytesToString(a)},_blocksize:4,_encryptblock:function(a,b){for(var c=0;c<s._blocksize;c++)for(var d=0;4>d;d++)i[c][d]=a[b+4*d+c];for(c=0;4>c;c++)for(d=0;4>d;d++)i[c][d]^=p[d][c];for(var f=1;f<r;f++){for(c=0;4>c;c++)for(d=0;4>d;d++)i[c][d]=e[i[c][d]];i[1].push(i[1].shift());i[2].push(i[2].shift());
i[2].push(i[2].shift());i[3].unshift(i[3].pop());for(d=0;4>d;d++){var c=i[0][d],g=i[1][d],k=i[2][d],l=i[3][d];i[0][d]=h[c]^j[g]^k^l;i[1][d]=c^h[g]^j[k]^l;i[2][d]=c^g^h[k]^j[l];i[3][d]=j[c]^g^k^h[l]}for(c=0;4>c;c++)for(d=0;4>d;d++)i[c][d]^=p[4*f+d][c]}for(c=0;4>c;c++)for(d=0;4>d;d++)i[c][d]=e[i[c][d]];i[1].push(i[1].shift());i[2].push(i[2].shift());i[2].push(i[2].shift());i[3].unshift(i[3].pop());for(c=0;4>c;c++)for(d=0;4>d;d++)i[c][d]^=p[4*r+d][c];for(c=0;c<s._blocksize;c++)for(d=0;4>d;d++)a[b+4*
d+c]=i[c][d]},_decryptblock:function(a,c){for(var b=0;b<s._blocksize;b++)for(var d=0;4>d;d++)i[b][d]=a[c+4*d+b];for(b=0;4>b;b++)for(d=0;4>d;d++)i[b][d]^=p[4*r+d][b];for(var e=1;e<r;e++){i[1].unshift(i[1].pop());i[2].push(i[2].shift());i[2].push(i[2].shift());i[3].push(i[3].shift());for(b=0;4>b;b++)for(d=0;4>d;d++)i[b][d]=g[i[b][d]];for(b=0;4>b;b++)for(d=0;4>d;d++)i[b][d]^=p[4*(r-e)+d][b];for(d=0;4>d;d++){var b=i[0][d],f=i[1][d],h=i[2][d],j=i[3][d];i[0][d]=l[b]^k[f]^n[h]^m[j];i[1][d]=m[b]^l[f]^k[h]^
n[j];i[2][d]=n[b]^m[f]^l[h]^k[j];i[3][d]=k[b]^n[f]^m[h]^l[j]}}i[1].unshift(i[1].pop());i[2].push(i[2].shift());i[2].push(i[2].shift());i[3].push(i[3].shift());for(b=0;4>b;b++)for(d=0;4>d;d++)i[b][d]=g[i[b][d]];for(b=0;4>b;b++)for(d=0;4>d;d++)i[b][d]^=p[d][b];for(b=0;b<s._blocksize;b++)for(d=0;4>d;d++)a[c+4*d+b]=i[b][d]},_init:function(a){o=a.length/4;r=o+6;s._keyexpansion(a)},_keyexpansion:function(a){p=[];for(var b=0;b<o;b++)p[b]=[a[4*b],a[4*b+1],a[4*b+2],a[4*b+3]];for(b=o;b<s._blocksize*(r+1);b++)a=
[p[b-1][0],p[b-1][1],p[b-1][2],p[b-1][3]],0==b%o?(a.push(a.shift()),a[0]=e[a[0]],a[1]=e[a[1]],a[2]=e[a[2]],a[3]=e[a[3]],a[0]^=q[b/o]):6<o&&4==b%o&&(a[0]=e[a[0]],a[1]=e[a[1]],a[2]=e[a[2]],a[3]=e[a[3]]),p[b]=[p[b-o][0]^a[0],p[b-o][1]^a[1],p[b-o][2]^a[2],p[b-o][3]^a[3]]}}})();if("function"==typeof require&&"undefined"==typeof AtmosUtil)AtmosUtil=require("./AtmosUtil").AtmosUtil;AccessToken=function(a,b,c,d,e){this.tokenId=a;this.tokenPolicy=b;this.objectPath=c;this.objectId=d;this.acl=e};
AccessToken.fromNode=function(a){var b=new AccessToken,c,d,e;if(c=AtmosUtil.getChildByTagName(a,"access-token-id"))b.tokenId=AtmosUtil.getTextContent(c);if(c=AtmosUtil.getChildByTagName(a,"path"))b.objectPath=AtmosUtil.getTextContent(c);if(c=AtmosUtil.getChildByTagName(a,"object-id"))b.objectId=AtmosUtil.getTextContent(c);if(c=AtmosUtil.getChildByTagName(a,"useracl"))d=AccessToken._parseAclEntries(AtmosUtil.getTextContent(c));if(c=AtmosUtil.getChildByTagName(a,"groupacl"))e=AccessToken._parseAclEntries(AtmosUtil.getTextContent(c));
if(d||e)b.acl=new Acl(d,e);b.tokenPolicy=AccessTokenPolicy.fromNode(a);return b};AccessToken._parseAclEntries=function(a){for(var b=[],a=a.split(/ *, */),c=0;c<a.length;c++){var d=a[c].split("=",2),e=d[0],d=d[1],e=e.trim();if("FULL"===d)d=AclEntry.ACL_PERMISSIONS.FULL_CONTROL;b[c]=new AclEntry(e,d)}return b};
AccessTokenPolicy=function(a,b,c,d,e,g,f,h){this.expiration=a;this.maxUploads=b;this.maxDownloads=c;this.sourceAllowList=d;this.sourceDenyList=e;this.minSize=g;this.maxSize=f;this.formFieldList=h};
AccessTokenPolicy.fromNode=function(a){var b=new AccessTokenPolicy,c,d;if(c=AtmosUtil.getChildByTagName(a,"expiration"))b.expiration=AtmosUtil.parseIso8601Date(AtmosUtil.getTextContent(c));if(c=AtmosUtil.getChildByTagName(a,"max-uploads"))b.maxUploads=parseInt(AtmosUtil.getTextContent(c));if(c=AtmosUtil.getChildByTagName(a,"max-downloads"))b.maxDownloads=parseInt(AtmosUtil.getTextContent(c));if(c=AtmosUtil.getChildByTagName(a,"source")){if(d=AtmosUtil.getChildrenByTagName(c,"allow"))b.sourceAllowList=
[],d.forEach(function(a){b.sourceAllowList.push(AtmosUtil.getTextContent(a))});if(d=AtmosUtil.getChildrenByTagName(c,"disallow"))b.sourceDenyList=[],d.forEach(function(a){b.sourceDenyList.push(AtmosUtil.getTextContent(a))})}if(c=AtmosUtil.getChildByTagName(a,"content-length-range"))b.minSize=parseInt(c.getAttribute("from")),b.maxSize=parseInt(c.getAttribute("to"));if(d=AtmosUtil.getChildrenByTagName(a,"form-field"))b.formFieldList=[],d.forEach(function(a){b.formFieldList.push(AccessTokenFormField.fromElement(a))});
return b};
AccessTokenPolicy.prototype.toDocument=function(){var a=AtmosUtil.createDocument(),b=AtmosUtil.createElement(a,"policy");a.appendChild(b);this.expiration&&b.appendChild(AtmosUtil.createElement(a,"expiration",this.expiration.toISOString()));this.maxUploads&&b.appendChild(AtmosUtil.createElement(a,"max-uploads",this.maxUploads));this.maxDownloads&&b.appendChild(AtmosUtil.createElement(a,"max-downloads",this.maxDownloads));if(this.sourceAllowList&&this.sourceAllowList.length||this.sourceDenyList&&this.sourceDenyList.length){var c=
AtmosUtil.createElement(a,"source");b.appendChild(c);this.sourceAllowList&&this.sourceAllowList.forEach(function(b){c.appendChild(AtmosUtil.createElement(a,"allow",b))});this.sourceDenyList&&this.sourceDenyList.forEach(function(b){c.appendChild(AtmosUtil.createElement(a,"disallow",b))})}if("number"==typeof this.minSize||"number"==typeof this.maxSize){var d={};if("number"==typeof this.minSize)d.from=this.minSize;if("number"==typeof this.maxSize)d.to=this.maxSize;b.appendChild(AtmosUtil.createElement(a,
"content-length-range",null,d))}this.formFieldList&&this.formFieldList.forEach(function(c){b.appendChild(c.toElement(a))});return a};AccessTokenFormField=function(a,b,c,d,e,g,f){this.name=a;this.optional=b;this.eq=c;this.startsWith=d;this.endsWith=e;this.contains=g;this.matches=f};
AccessTokenFormField.fromElement=function(a){var b=new AccessTokenFormField(a.getAttribute("name"),a.getAttribute("optional")?!0:!1),c;if(c=AtmosUtil.getChildByTagName(a,"eq"))b.eq=AtmosUtil.getTextContent(c);if(c=AtmosUtil.getChildByTagName(a,"starts-with"))b.startsWith=AtmosUtil.getTextContent(c);if(c=AtmosUtil.getChildByTagName(a,"ends-with"))b.endsWith=AtmosUtil.getTextContent(c);if(c=AtmosUtil.getChildByTagName(a,"contains"))b.contains=AtmosUtil.getTextContent(c);if(c=AtmosUtil.getChildByTagName(a,
"matches"))b.matches=AtmosUtil.getTextContent(c);return b};
AccessTokenFormField.prototype.toElement=function(a){var b=AtmosUtil.createElement(a,"form-field",null,{name:this.name});this.optional&&b.setAttribute("optional","true");this.eq?b.appendChild(AtmosUtil.createElement(a,"eq",this.eq)):this.startsWith?b.appendChild(AtmosUtil.createElement(a,"starts-with",this.startsWith)):this.endsWith?b.appendChild(AtmosUtil.createElement(a,"ends-with",this.endsWith)):this.contains?b.appendChild(AtmosUtil.createElement(a,"contains",this.contains)):this.matches&&b.appendChild(AtmosUtil.createElement(a,
"matches",this.matches));return b};if("undefined"!=typeof exports)exports.AccessToken=AccessToken,exports.AccessTokenPolicy=AccessTokenPolicy,exports.AccessTokenFormField=AccessTokenFormField;Acl=function(a,b){this.userEntries=a;this.groupEntries=b};AclEntry=function(a,b){this.key=a;this.value=b};AclEntry.ACL_PERMISSIONS={READ:"READ",WRITE:"WRITE",FULL_CONTROL:"FULL_CONTROL",NONE:"NONE"};AclEntry.GROUPS={OTHER:"other"};if("undefined"!=typeof exports)exports.Acl=Acl,exports.AclEntry=AclEntry;AtmosConfig=function(a,b,c,d,e,g,f){this.uid=a;this.secret=b;this.enableUtf8=c;this.enableDebug=d;this.protocol=e;this.host=g;this.port=f};if("undefined"!=typeof exports)exports.AtmosConfig=AtmosConfig;var isNodejs="function"==typeof require;if(isNodejs&&(crypto=require("crypto"),XMLHttpRequest=require("xmlhttprequest").XMLHttpRequest,"undefined"==typeof AtmosUtil))AtmosUtil=require("./AtmosUtil").AtmosUtil;AtmosRest=function(a){this.atmosConfig=a;this.info("AtmosRest loaded")};var ATMOS_REST_VERSION="2.1.1";AtmosRest.version=ATMOS_REST_VERSION;var ATMOS_REST_COMPILED=!0;AtmosRest.compiled=ATMOS_REST_COMPILED;AtmosRest.iframeCount=0;AtmosRest.prototype.context="/rest";
AtmosRest.prototype.getServiceInformation=function(a){var b=this;this._ajax({method:"GET",uri:this.context+"/service",headers:{},processResult:function(a,d){if(a.successful){var e="n/a",g=b._getXmlDoc(d).getElementsByTagName("Version");g.length&&(e=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(g[0],"Atmos")));a.value=new AtmosServiceInfo(e,!1,!1,!1,!1,!1);a.value.loadFeaturesFromHeader(d.getResponseHeader("x-emc-features"),d.getResponseHeader("x-emc-support-utf8"))}},complete:a})};
AtmosRest.prototype.createObject=function(a,b,c,d,e,g,f,h){var j={},m=this;this._addAclHeaders(a,j);this._addMetadataHeaders(b,j,!1);this._addMetadataHeaders(c,j,!0);this._ajax({uri:this.context+"/objects",method:"POST",headers:j,data:e,mimeType:g,progress:h,processResult:function(a,b){a.successful&&m._processCreateObjectResult(a,b)},complete:f,form:d})};
AtmosRest.prototype.createObjectOnPath=function(a,b,c,d,e,g,f,h,j){if(!AtmosRest.objectPathMatch.test(a))throw"The path '"+a+"' is not valid";var m={},k=this;this._addAclHeaders(b,m);this._addMetadataHeaders(c,m,!1);this._addMetadataHeaders(d,m,!0);this._ajax({uri:this._getPath(a),method:"POST",headers:m,data:g,mimeType:f,progress:j,processResult:function(a,b){a.successful&&k._processCreateObjectResult(a,b)},complete:h,form:e})};
AtmosRest.prototype.readObject=function(a,b,c){this._ajax({uri:this._getPath(a),method:"GET",headers:{},range:b,processResult:function(a,b){if(a.successful)a.data=b.responseText},complete:c})};AtmosRest.prototype.updateObject=function(a,b,c,d,e,g,f,h,j,m){var k={};this._addAclHeaders(b,k);this._addMetadataHeaders(c,k,!1);this._addMetadataHeaders(d,k,!0);this._ajax({uri:this._getPath(a),method:"PUT",headers:k,data:g,mimeType:h,range:f,progress:m,complete:j,form:e})};
AtmosRest.prototype.deleteObject=function(a,b){this._ajax({uri:this._getPath(a),method:"DELETE",headers:{},complete:b})};AtmosRest.prototype.listVersions=function(a,b){var c=this;this._ajax({uri:this._getPath(a)+"?versions",method:"GET",headers:{},processResult:function(a,b){if(a.successful)a.value=c._parseObjectVersions(b)},complete:b})};
AtmosRest.prototype.versionObject=function(a,b){var c=this;this._ajax({uri:this._getPath(a)+"?versions",method:"POST",headers:{},processResult:function(a,b){a.successful&&c._processCreateObjectResult(a,b)},complete:b})};AtmosRest.prototype.restoreVersion=function(a,b,c){var d={};d["x-emc-version-oid"]=b;this._ajax({uri:this._getPath(a)+"?versions",method:"PUT",headers:d,complete:c})};
AtmosRest.prototype.deleteVersion=function(a,b){this._ajax({uri:this._getPath(a)+"?versions",method:"DELETE",headers:{},complete:b})};AtmosRest.prototype.rename=function(a,b,c,d){if(!AtmosRest.objectPathMatch.test(b))throw"The path '"+b+"' is not valid";var e={};e["x-emc-path"]=this.atmosConfig.enableUtf8?encodeURIComponent(b.substr(1)):b.substr(1);c&&(e["x-emc-force"]="true");this._ajax({uri:this._getPath(a)+"?rename",method:"POST",headers:e,complete:d})};
AtmosRest.prototype.createAttachmentDisposition=function(a){return a?"attachment; filename*="+encodeURIComponent("UTF-8''"+a):"attachment"};
AtmosRest.prototype.getShareableUrl=function(a,b,c){if(!b.getTime)throw"expirationDate must be a Date object";var a=this._getPath(a),b=Math.floor(b.getTime()/1E3),d="GET\n"+a.toLowerCase()+"\n"+this.atmosConfig.uid+"\n"+b;c&&(d+="\n"+c);this.debug("hash string:\n"+d);var d=this._doSignature(d,this.atmosConfig.secret),e="uid="+encodeURIComponent(this.atmosConfig.uid),e=e+("&expires="+b)+("&signature="+encodeURIComponent(d));c&&(e+="&disposition="+encodeURIComponent(c));c=this._resolveUrl(this._encodeURI(a),
e);this.debug("Shareable URL: "+c);return c};AtmosRest.prototype.getAcl=function(a,b){var c=this;this._ajax({uri:this._getPath(a)+"?acl",method:"GET",headers:{},processResult:function(a,b){if(a.successful){var g=c._parseAclEntries(b.getResponseHeader("x-emc-useracl")),f=c._parseAclEntries(b.getResponseHeader("x-emc-groupacl"));a.value=new Acl(g,f)}},complete:b,x:2})};
AtmosRest.prototype.setAcl=function(a,b,c){var d={};this._addAclHeaders(b,d);this._ajax({uri:this._getPath(a)+"?acl",method:"POST",headers:d,complete:c})};
AtmosRest.prototype.listUserMetadataTags=function(a,b){var c=this;this._ajax({uri:this._getPath(a)+"?metadata/tags",method:"GET",headers:{},processResult:function(a,b){if(a.successful){var g="true"==b.getResponseHeader("x-emc-utf8");a.value={};var f=b.getResponseHeader("x-emc-tags");if(f)a.value.tags=c._listToArray(f,g);if(f=b.getResponseHeader("x-emc-listable-tags"))a.value.listableTags=c._listToArray(f,g)}},complete:b})};
AtmosRest.prototype.getUserMetadata=function(a,b,c){var d={},e=this;b&&this._addTagHeader(b,d);this._ajax({uri:this._getPath(a)+"?metadata/user",method:"GET",headers:d,processResult:function(a,b){if(a.successful){var c="true"==b.getResponseHeader("x-emc-utf8");a.value={};a.value.meta=e._parseMetadata(b.getResponseHeader("x-emc-meta"),c);a.value.listableMeta=e._parseMetadata(b.getResponseHeader("x-emc-listable-meta"),c)}},complete:c})};
AtmosRest.prototype.getSystemMetadata=function(a,b,c){var d={},e=this;b&&this._addTagHeader(b,d);this._ajax({uri:this._getPath(a)+"?metadata/system",method:"GET",headers:d,processResult:function(a,b){if(a.successful){var c="true"==b.getResponseHeader("x-emc-utf8");a.value={};a.value.systemMeta=e._parseMetadata(b.getResponseHeader("x-emc-meta"),c);a.value.systemMeta.mimeType=b.getResponseHeader("Content-Type")}},complete:c})};
AtmosRest.prototype.getAllMetadata=function(a,b){var c=this;this._ajax({uri:this._getPath(a),method:"HEAD",headers:{},processResult:function(a,b){if(a.successful){var g="true"==b.getResponseHeader("x-emc-utf8");a.value={};a.value.meta=c._parseMetadata(b.getResponseHeader("x-emc-meta"),g);a.value.listableMeta=c._parseMetadata(b.getResponseHeader("x-emc-listable-meta"),g);var g=c._parseAclEntries(b.getResponseHeader("x-emc-useracl")),f=c._parseAclEntries(b.getResponseHeader("x-emc-groupacl"));a.value.acl=
new Acl(g,f)}},complete:b})};AtmosRest.prototype.getObjectInfo=function(a,b){var c=this;this._ajax({uri:this._getPath(a)+"?info",method:"GET",headers:{},processResult:function(a,b){a.successful&&c._processObjectInfoResult(a,b)},complete:b})};AtmosRest.prototype.setUserMetadata=function(a,b,c,d){var e={};this._addMetadataHeaders(b,e,!1);this._addMetadataHeaders(c,e,!0);this._ajax({uri:this._getPath(a)+"?metadata/user",method:"POST",headers:e,complete:d})};
AtmosRest.prototype.deleteUserMetadata=function(a,b,c){var d={};this._addTagHeader(b,d);this._ajax({uri:this._getPath(a)+"?metadata/user",method:"DELETE",headers:d,complete:c})};
AtmosRest.prototype.getListableTags=function(a,b){var c={},d=this;a&&this._addTagHeader([a],c);this._ajax({uri:this.context+"/objects?listabletags",method:"GET",headers:c,processResult:function(a,b){if(a.successful){var c="true"==b.getResponseHeader("x-emc-utf8"),h=b.getResponseHeader("x-emc-listable-tags");if(h)a.value=d._listToArray(h,c)}},complete:b})};
AtmosRest.prototype.listObjects=function(a,b,c){if(!a)throw"Tag cannot be null";var d={},e=this;this._addTagHeader([a],d);this._addListOptionHeaders(d,b);this._ajax({uri:this.context+"/objects",method:"GET",headers:d,processResult:function(a,b){a.successful&&e._processListObjectsResult(a,b)},complete:c})};
AtmosRest.prototype.listDirectory=function(a,b,c){if(!a)throw"Directory cannot be null";if("/"!==a.charAt(a.length-1))throw"Directory must end with a slash";var d={},e=this;this._addListOptionHeaders(d,b);this._ajax({uri:this.context+"/namespace"+a,method:"GET",headers:d,processResult:function(b,c){b.successful&&e._processListDirectoryResult(a,b,c)},complete:c})};
AtmosRest.prototype.createAccessToken=function(a,b,c,d,e,g){var f={},h=this;b&&(AtmosRest.objectPathMatch.test(b)?f["x-emc-path"]=this.atmosConfig.enableUtf8?encodeURIComponent(b):b:f["x-emc-objectid"]=b);this._addAclHeaders(c,f);this._addMetadataHeaders(d,f,!1);this._addMetadataHeaders(e,f,!0);this._ajax({uri:this.context+"/accesstokens",method:"POST",headers:f,data:AtmosUtil.serializeXml(a.toDocument()),mimeType:"application/xml",processResult:function(a,b){if(a.successful)a.value=h._resolveUrl(b.getResponseHeader("location"))},
complete:g})};AtmosRest.prototype.getAccessToken=function(a,b){a||(a="");var c=a.split("/"),d=this;this._ajax({uri:this.context+"/accesstokens/"+c[c.length-1]+"?info",method:"GET",headers:{},processResult:function(a,b){if(a.successful)a.value=AccessToken.fromNode(AtmosUtil.getChildByTagName(d._getXmlDoc(b),"access-token"))},complete:b})};AtmosRest.prototype.deleteAccessToken=function(a,b){var c=a.split("/");this._ajax({uri:this.context+"/accesstokens/"+c[c.length-1],method:"DELETE",headers:{},complete:b})};
AtmosRest.prototype.listAccessTokens=function(a,b){var c={},d=this;this._addListOptionHeaders(c,a);this._ajax({uri:this.context+"/accesstokens",method:"GET",headers:c,processResult:function(a,b){if(a.successful){a.token=b.getResponseHeader("x-emc-token");var c=AtmosUtil.getChildByTagName(d._getXmlDoc(b),"list-access-tokens-result"),c=AtmosUtil.getChildByTagName(c,"access-tokens-list"),h=[];AtmosUtil.getChildrenByTagName(c,"access-token").forEach(function(a){h.push(AccessToken.fromNode(a))});a.value=
h}},complete:b})};AtmosRest.locationMatch=/^\/rest\/objects\/(.*)/;AtmosRest.objectPathMatch=/^\//;AtmosRest.prototype._getPath=function(a){return AtmosRest.objectPathMatch.test(a)?this.context+"/namespace"+a:this.context+"/objects/"+a};AtmosRest.prototype._addAclHeaders=function(a,b){null!=a&&(b["x-emc-useracl"]=this._mapEntriesToString(a.userEntries),b["x-emc-groupacl"]=this._mapEntriesToString(a.groupEntries))};
AtmosRest.prototype._mapEntriesToString=function(a){if(void 0==a||1>a.length)return null;for(var b=[],c=0;c<a.length;c++)b.push(a[c].key+"="+a[c].value);return b.join(",")};AtmosRest.prototype._addTagHeader=function(a,b){for(var c="",d=0;d<a.length;d++)0<d&&(c+=","),c+=this.atmosConfig.enableUtf8?encodeURIComponent(a[d]):a[d];b["x-emc-tags"]=c};
AtmosRest.prototype._addMetadataHeaders=function(a,b,c){null==a||0==Object.keys(a).length||(c?b["x-emc-listable-meta"]=this._metaToHeaderValue(a):b["x-emc-meta"]=this._metaToHeaderValue(a))};AtmosRest.prototype._metaToHeaderValue=function(a){for(var b=[],c=Object.keys(a),d=0;d<c.length;d++){var e=this.atmosConfig.enableUtf8?encodeURIComponent(c[d]):c[d],g=this.atmosConfig.enableUtf8?encodeURIComponent(a[c[d]]):a[c[d]];b.push(e+"="+g)}return b.join(",")};
AtmosRest.prototype._listToArray=function(a,b){if(!a)return null;if(0==a.trim().length)return[];for(var c=a.split(","),d=0;d<c.length;d++)c[d]=b?decodeURIComponent(c[d].trim()):c[d].trim();return c};AtmosRest.prototype._addListOptionHeaders=function(a,b){if(b){b.limit&&(a["x-emc-limit"]=""+b.limit);if(b.token)a["x-emc-token"]=b.token;b.includeMeta&&(a["x-emc-include-meta"]="1",b.userMetaTags&&(a["x-emc-user-tags"]=b.userMetaTags.join(",")),b.systemMetaTags&&(a["x-emc-system-tags"]=b.systemMetaTags.join(",")))}};
AtmosRest.prototype._prepBaseHeaders=function(a,b){a["x-emc-date"]=(new Date).toGMTString();b&&(a.Range=b.toString())};AtmosRest.prototype._prepUploadHeaders=function(a,b){if(""==b||void 0==b)b="text/plain; charset=UTF-8";-1==b.indexOf("charset")&&(b+="; charset=UTF-8");a["Content-Type"]=b};
AtmosRest.prototype._ajax=function(a){a.uri=this._resolveDots(a.uri);a.headers&&(this.atmosConfig.enableUtf8&&(a.headers["x-emc-utf8"]="true"),this._prepBaseHeaders(a.headers,a.range),/(POST|PUT)/.test(a.method)&&this._prepUploadHeaders(a.headers,a.mimeType),this._signRequest(a.method,a.headers,a.uri));if(!/^https?:\/\//.test(a.uri)&&(a.uri=this._encodeURI(a.uri),this.atmosConfig.host&&this.atmosConfig.protocol)){var b=this.atmosConfig.protocol+"//"+this.atmosConfig.host;this.atmosConfig.port&&(b+=
":"+this.atmosConfig.port);a.uri=b+a.uri}var c=this,d=function(b){var d=c._createResult(b,400>b.status);a.processResult&&a.processResult(d,b);a.complete&&a.complete(d)};if(a.form){a.headers["x-http-inject-response-headers"]="true";if("POST"!=a.method)a.headers["x-http-method-override"]=a.method;b=this._createTargetIframe(function(a){a=c._parseFormResponse(a);d(a)});this._setFormHeaders(a.form,a.headers);a.progress&&a.progress(-1);a.form.action=a.uri;a.form.method="POST";a.form.enctype=a.form.encoding=
"multipart/form-data";a.form.target=b.name;a.form.submit();this._unsetFormHeaders(a.form,a.headers)}else{var e=this._getXMLHttpRequest();e.onreadystatechange=function(){4==e.readyState&&d(e)};try{if(a.progress)(e.upload||e).onprogress=function(b){b.lengthComputable&&a.progress(Math.floor(100*((b.position||b.loaded)/(b.totalSize||b.total))))}}catch(g){a.progress(-1)}e.open(a.method,a.uri,!0);this._setHeaders(e,a.headers);a.data?e.send(a.data):e.send()}};
AtmosRest.prototype._getXMLHttpRequest=function(){if(isNodejs)return new XMLHttpRequest;if(window.XMLHttpRequest)return new window.XMLHttpRequest;try{return new ActiveXObject("MSXML2.XMLHTTP.3.0")}catch(a){return null}};
AtmosRest.prototype._setFormHeaders=function(a,b){for(var c=Object.keys(b),d=0;d<c.length;d++){var e=a.elements[c[d]];if(!e){try{e=document.createElement('<input type="hidden" name="'+c[d]+'">')}catch(g){e=document.createElement("input"),e.name=c[d]}e.type="hidden";a.insertBefore(e,a.childNodes[0])}e.value=b[c[d]]}};AtmosRest.prototype._unsetFormHeaders=function(a,b){for(var c=Object.keys(b),d=0;d<c.length;d++){var e=a.elements[c[d]];e&&a.removeChild(e)}};
AtmosRest.prototype._createTargetIframe=function(a){var b="ATMOS_IFRAME_"+ ++AtmosRest.iframeCount,c;try{c=document.createElement('<iframe name="'+b+'"></iframe>')}catch(d){c=document.createElement("iframe"),c.name=b}c.id=b;c.style.display="none";document.body.appendChild(c);b=function(){var b=c.contentDocument||c.contentWindow.document;a.call(c,null!=b.body?b.body.firstChild.innerHTML:b.documentElement.innerHTML);document.body.removeChild(c)};c.attachEvent?c.attachEvent("onload",b):c.onload=b;return c};
AtmosRest.prototype._parseFormResponse=function(a){this.debug("form response (raw):\n"+a);var b={headers:{}},c;try{var d=0,e=function(b){var c=a.indexOf("\n");if(0>c)c=a.length;var e=a.substr(0,c);b&&(a=a.substr(c+1),d+=c+1);"\r"==e.charAt(e.length-1)&&(e=e.substr(0,e.length-1));return e};c=parseInt(e(!1));if(!isNaN(c)){e(!0);var g=e(!0),f=g.split(" ");b.status=parseInt(f[1]);for(b.statusText=g.substr(f[0].length+f[1].length+2);d<c;){var h=e(!0),j=h.indexOf(": ");b.headers[h.substr(0,j)]=h.substr(j+
2)}}}catch(m){this.warn("could not parse headers in form response: "+m)}b.getResponseHeader=function(a){return this.headers[a]};b.responseText=this._decodeXmlEntities(a);return b};AtmosRest.prototype._decodeXmlEntities=function(a){a=a.replace(/&gt;/g,">");return a=a.replace(/&lt;/g,"<")};AtmosRest.prototype._resolveDots=function(a){if(!a)return a;for(var a=a.split("/"),b=0;b<a.length;b++)".."==a[b]?(a.splice(b-1,2),b-=2):"."==a[b]&&a.splice(b--,1);return a.join("/")};
AtmosRest.prototype._setHeaders=function(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&a.setRequestHeader(c,b[c])};AtmosRest.prototype._encodeURI=function(a){this.debug("encodeURI: in: "+a);var b=a.indexOf("?"),c="";-1!=b&&(c=a.substring(b),a=a.substring(0,b));for(var a=a.split("/"),d=0;d<a.length;d++)a[d]=encodeURIComponent(a[d]);a=a.join("/");-1!=b&&(a+=encodeURI(c));this.debug("encodeURI: out: "+a);return a};
AtmosRest.prototype._createResult=function(a,b){var c=new AtmosResult(b);c.httpCode=a.status;c.httpMessage=a.statusText;if(!b){var d=this._getXmlDoc(a).getElementsByTagName("Error");if(d.length)c.errorCode=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(d[0],"Code")),c.errorMessage=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(d[0],"Message"))}return c};AtmosRest.prototype._getXmlDoc=function(a){if(a.responseXML)return a.responseXML;this.debug("response:\n"+a.responseText);return AtmosUtil.parseXml(a.responseText)};
AtmosRest.prototype._processCreateObjectResult=function(a,b){var c=b.getResponseHeader("location");this.debug("location: "+c);var d=c.match(AtmosRest.locationMatch);d?(a.value=d[1],this.debug("Location: "+a.value)):(a.successful=!1,a.message="Could not find location in "+c)};
AtmosRest.prototype._parseMetadata=function(a,b){if("undefined"==typeof a||null==a||0==a.length)return null;for(var c={},d=a.split(","),e=0;e<d.length;e++){var g=d[e].split("=",2),f=b?decodeURIComponent(g[0].trim()):g[0].trim();c[f]=1==g.length?"":b?decodeURIComponent(g[1]):g[1]}return c};
AtmosRest.prototype._processListObjectsResult=function(a,b){a.token=b.getResponseHeader("x-emc-token");for(var c=[],d=this._getXmlDoc(b).getElementsByTagName("Object"),e=0;e<d.length;e++){var g=null,f=null,h=null,j=d.item(e),m=AtmosUtil.getChildByTagName(j,"ObjectID"),k=AtmosUtil.getChildByTagName(j,"SystemMetadataList"),j=AtmosUtil.getChildByTagName(j,"UserMetadataList");k&&(f={},this._parseResponseMeta(k.childNodes,f,null));j&&(g={},h={},this._parseResponseMeta(j.childNodes,g,h));g=new ObjectResult(AtmosUtil.getTextContent(m),
g,h,f);c.push(g)}a.value=c};
AtmosRest.prototype._processListDirectoryResult=function(a,b,c){b.token=c.getResponseHeader("x-emc-token");for(var d=[],c=this._getXmlDoc(c).getElementsByTagName("DirectoryEntry"),e=0;e<c.length;e++){var g=null,f=null,h=null,j=c.item(e),m=AtmosUtil.getChildByTagName(j,"ObjectID"),k=AtmosUtil.getChildByTagName(j,"Filename"),n=AtmosUtil.getChildByTagName(j,"FileType"),l=AtmosUtil.getChildByTagName(j,"SystemMetadataList"),j=AtmosUtil.getChildByTagName(j,"UserMetadataList");l&&(f={},this._parseResponseMeta(l.childNodes,
f,null));j&&(g={},h={},this._parseResponseMeta(j.childNodes,g,h));g=new DirectoryItem(a+AtmosUtil.getTextContent(k),AtmosUtil.getTextContent(k),AtmosUtil.getTextContent(n),AtmosUtil.getTextContent(m),g,h,f);d.push(g)}b.value=d};
AtmosRest.prototype._processObjectInfoResult=function(a,b){var c=this._getXmlDoc(b),d=null,e=null,g=[],f=!1,h=null,j=!1,m=null,k=c.getElementsByTagName("objectId");k.length&&(d=AtmosUtil.getTextContent(k.item(0)));k=c.getElementsByTagName("selection");k.length&&(e=AtmosUtil.getTextContent(k.item(0)));k=c.getElementsByTagName("replicas");if(k.length)for(var k=AtmosUtil.getChildrenByTagName(k.item(0),"replica"),n=0;n<k.length;n++){var l=k[n],q=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,
"id")),i=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,"location")),o=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,"type")),r=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,"current")),l=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,"storageType"));g.push(new ObjectReplica(q,i,o,r,l))}k=c.getElementsByTagName("expiration");k.length&&(l=k.item(0),f=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,"enabled")),h=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,
"endAt")));k=c.getElementsByTagName("retention");k.length&&(l=k.item(0),j=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,"enabled")),m=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(l,"endAt")));a.value=new ObjectInfo(d,e,g,f,h,j,m)};
AtmosRest.prototype._parseObjectVersions=function(a){for(var b=[],a=this._getXmlDoc(a).getElementsByTagName("Ver"),c=0;c<a.length;c++)b.push({num:AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(a.item(c),"VerNum")),oid:AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(a.item(c),"OID")),dateCreated:AtmosUtil.parseIso8601Date(AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(a.item(c),"itime")))});return b};
AtmosRest.prototype._parseAclEntries=function(a){for(var b=[],a=this._listToArray(a),c=0;c<a.length;c++){var d=a[c].split("=",2),e=d[0],d=d[1],e=e.trim();if("FULL"===d)d=AclEntry.ACL_PERMISSIONS.FULL_CONTROL;b[c]=new AclEntry(e,d)}return b};
AtmosRest.prototype._parseResponseMeta=function(a,b,c){for(var d=0;d<a.length;d++){var e=a.item(d);if(/Metadata/i.test(e.nodeName)){var g=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(e,"Name")),f=AtmosUtil.getTextContent(AtmosUtil.getChildByTagName(e,"Value"));(e=AtmosUtil.getChildByTagName(e,"Listable"))&&"true"==AtmosUtil.getTextContent(e)?c[g]=f:b[g]=f}}};
AtmosRest.prototype._signRequest=function(a,b,c){this.debug(this.atmosConfig.uid);this.debug(this.atmosConfig.secret);b["x-emc-uid"]=this.atmosConfig.uid;a=this._buildHashString(a,c,b);this.debug("HashString:\n"+a);a=this._doSignature(a,this.atmosConfig.secret);this.debug("Signature: "+a);return b["x-emc-signature"]=a};
AtmosRest.prototype._buildHashString=function(a,b,c){var d=c["Content-Type"],e=c.Range,g=c.Date,f={},h="",h=a+"\n",h=d?h+(d+"\n"):h+"\n",h=e?h+(e.toString()+"\n"):h+"\n",h=g?h+(g+"\n"):h+"\n",h=h+(b.toLowerCase().trim()+"\n"),j;for(j in c)c.hasOwnProperty(j)&&(this.debug("headers: prop: "+j+" value: "+c[j]),a=this._normalizeWS(j.toLowerCase().trim()),0!=a.indexOf("x-emc")?this.debug("Skipping "+a):((b=c[j])&&(b=this._normalizeWS(b.trim())),f[a]=b));c=Object.keys(f);this.debug("keys "+c);c.sort().forEach(function(a){h+=
a+":"+f[a]+"\n"});return h.trim()};AtmosRest.prototype._normalizeWS=function(a){if(null==a)return null;a=a.replace(/\n/," ");return a.replace(/\s+/," ")};AtmosRest.prototype._doSignature=function(a,b){this.debug("Secret: "+b);if(isNodejs){var c=new Buffer(b,"base64"),c=crypto.createHmac("sha1",c.toString("binary"));c.update(a,"utf8");return c.digest("base64")}c=Crypto.HMAC(Crypto.SHA1,a,Crypto.util.base64ToBytes(b),{asBytes:!0});return Crypto.util.bytesToBase64(c)};
AtmosRest.prototype._resolveUrl=function(a,b){var c="";this.atmosConfig.protocol&&this.atmosConfig.host?(c=this.atmosConfig.protocol+"//"+this.atmosConfig.host,this.atmosConfig.port&&(c+=":"+this.atmosConfig.port)):"undefined"!=typeof window&&(c=window.location.protocol+"//"+window.location.host,0<window.location.port&&(c+=":"+window.location.port));c+=a;b&&(c+="?"+b);return c};
AtmosRest.prototype.debug=function(a){this.atmosConfig.enableDebug&&"undefined"!==typeof console&&("undefined"!==typeof console.debug?console.debug(a):"undefined"!==typeof console.log&&console.log(a))};AtmosRest.prototype.info=function(a){"undefined"!==typeof console&&"undefined"!==typeof console.info&&console.info(a)};AtmosRest.prototype.warn=function(a){"undefined"!==typeof console&&"undefined"!==typeof console.warn&&console.warn(a)};
AtmosRest.prototype.error=function(a){"undefined"!==typeof console&&"undefined"!==typeof console.error&&console.error(a)};if("undefined"!=typeof exports)exports.AtmosRest=AtmosRest;AtmosResult=function(a,b,c,d){this.successful=a;this.value=b;this.message=c;this.token=d};if("undefined"!=typeof exports)exports.AtmosResult=AtmosResult;AtmosServiceInfo=function(a,b,c,d,e,g,f){this.version=a;this.object=b;this.namespace=c;this.utf8=d;this.browsercompat=e;this.keyvalue=g;this.versioning=f};AtmosServiceInfo.prototype.loadFeaturesFromHeader=function(a,b){if(a)for(var c=a.split(", "),d=0;d<c.length;d++)c[d]=c[d].replace(/-/g,""),this[c[d]]=!0;else this.namespace=this.object=!0,this.utf8="true"==b};if("undefined"!=typeof exports)exports.AtmosServiceInfo=AtmosServiceInfo;isNodeJs=!1;if("function"==typeof require){isNodeJs=!0;var dom=require("xmldom");DOMParser=dom.DOMParser;XMLSerializer=dom.XMLSerializer}
AtmosUtil={createDocument:function(){return isNodeJs?(new dom.DOMImplementation).createDocument("","",null):document.implementation.createDocument?document.implementation.createDocument("","",null):"undefined"!=typeof ActiveXObject?new ActiveXObject("MSXML.DomDocument"):null},createElement:function(a,b,c,d){b=a.createElement(b);c&&b.appendChild(a.createTextNode(c));if(d)for(var e in d)d.hasOwnProperty(e)&&b.setAttribute(e,d[e]);return b},parseXml:function(a){if(isNodeJs)return(new DOMParser).parseFromString(a);
if(window.DOMParser)return(new DOMParser).parseFromString(a,"text/xml");if("undefined"!=typeof ActiveXObject){var b=new ActiveXObject("MSXML.DomDocument");b.async=!1;b.loadXML(a);return b}return null},serializeXml:function(a){return isNodeJs||window.XMLSerializer?(new XMLSerializer).serializeToString(a):a.xml?a.xml:null},getChildByTagName:function(a,b){var c=AtmosUtil.getChildrenByTagName(a,b);return c.length?c[0]:null},getChildrenByTagName:function(a,b){for(var c=RegExp("^"+b+"$","i"),d=a.childNodes,
e=[],g=0;g<d.length;g++){var f=d.item(g);1==f.nodeType&&c.test(f.nodeName)&&e.push(f)}return e},getTextContent:function(a){for(var a=a.childNodes,b="",c=0;c<a.length;c++){var d=a.item(c);3==d.nodeType&&(b+=d.data)}return b},parseIso8601Date:function(a){var b=/^([0-9]{4})-([0-9]{2})-([0-9]{2})T([0-9]{2}):([0-9]{2}):([0-9]{2})(?:\.[0-9]{3})?(?:([+-][0-9]{2})([0-9]{2})|Z)$/.exec(a);if(b){var a=parseInt(b[1]),c=parseInt(b[2])-1,d=parseInt(b[3]),e=parseInt(b[4]),g=parseInt(b[5]),f=parseInt(b[6]),h=0,j=
0;b[7]&&(h=-parseInt(b[7]),j=parseInt(b[8]));b=new Date;b.setUTCFullYear(a,c,d);b.setUTCHours(e+h,g+j,f,0)}else b=new Date(a),b.setMilliseconds(0);return b}};if("undefined"!=typeof exports)exports.AtmosUtil=AtmosUtil;DirectoryItem=function(a,b,c,d,e,g,f){this.path=this.id=a;this.name=b;this.type=c;this.objectId=d;this.userMeta=e;this.listableUserMeta=g;this.systemMeta=f};if("undefined"!=typeof exports)exports.DirectoryItem=DirectoryItem;HttpRequest=function(a,b,c,d,e,g,f,h,j,m){this.uri=a;this.method=b;this.headers=c;this.data=d;this.mimeType=e;this.range=g;this.progress=f;this.processResult=h;this.complete=j;this.form=m};AtmosRange=function(a,b){this.offset=a;this.size=b};AtmosRange.prototype.toString=function(){return"bytes="+this.offset+"-"+(this.offset+this.size-1)};if("undefined"!=typeof exports)exports.HttpRequest=HttpRequest,exports.AtmosRange=AtmosRange;ListOptions=function(a,b,c,d,e){this.limit=a;this.token=b;this.includeMeta=c;this.userMetaTags=d;this.systemMetaTags=e};if("undefined"!=typeof exports)exports.ListOptions=ListOptions;ObjectInfo=function(a,b,c,d,e,g,f){this.objectId=a;this.selection=b;this.replicas=c;this.expirationEnabled=d;this.expirationEndsAt=e;this.retentionEnabled=g;this.retentionEndsAt=f};ObjectReplica=function(a,b,c,d,e){this.id=a;this.location=b;this.replicaType=c;this.current=d;this.storageType=e};if("undefined"!=typeof exports)exports.ObjectInfo=ObjectInfo,exports.ObjectReplica=ObjectReplica;ObjectResult=function(a,b,c,d){this.objectId=this.id=a;this.userMeta=b;this.listableUserMeta=c;this.systemMeta=d};if("undefined"!=typeof exports)exports.ObjectResult=ObjectResult;ObjectVersion=function(a,b,c){this.num=a;this.oid=b;this.dateCreated=c};if("undefined"!=typeof exports)exports.ObjectVersion=ObjectVersion;if(!Array.prototype.forEach)Array.prototype.forEach=function(a,b){for(var c=0,d=this.length;c<d;++c)a.call(b,this[c],c,this)};if(!String.prototype.trim)String.prototype.trim=function(){return this.replace(/^\s+|\s+$/g,"")};if(!String.prototype.startsWith)String.prototype.startsWith=function(a,b){b=b||0;return this.indexOf(a,b)===b};
if(!Object.keys)Object.keys=function(){var a=Object.prototype.hasOwnProperty,b=!{toString:null}.propertyIsEnumerable("toString"),c="toString,toLocaleString,valueOf,hasOwnProperty,isPrototypeOf,propertyIsEnumerable,constructor".split(","),d=c.length;return function(e){if("object"!==typeof e&&"function"!==typeof e||null===e)throw new TypeError("Object.keys called on non-object");var g=[],f;for(f in e)a.call(e,f)&&g.push(f);if(b)for(f=0;f<d;f++)a.call(e,c[f])&&g.push(c[f]);return g}}();
Date.prototype.toISOString||function(){function a(a){a=""+a;1===a.length&&(a="0"+a);return a}Date.prototype.toISOString=function(){return this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"."+(""+(this.getUTCMilliseconds()/1E3).toFixed(3)).slice(2,5)+"Z"}}();